### PR TITLE
FrameworkReference transitivity flow

### PR DESCRIPTION
**Pull request by nkolev92**
Spec for https://github.com/NuGet/Home/issues/7988

### CODE REVIEW

**Comment by dsplaisted** [comment]
Shouldn't this be .md instead of .txt, so that it shows up formatted in GitHub?

**Comment by nkolev92** [comment]
Yeah it should. Fixing it now :)

**Comment by nkolev92** [comment]
Fixed, it should be properly formatted now :)

**Comment by dsplaisted** [comment]
For the SDK, we would strongly prefer to continue to use `FrameworkReference` items for these.  Both the base and optional framework references have a lot of similarities in how we handle them - they both have targeting and runtime packs, for example.

As far as they surface in the user experience, they are also a similar concept.

**Comment by nkolev92** [comment]
Chatted with @dsplaisted offline. 
For now, we're only gonna do the NuGet side change.

**Pull request merged**
